using Application.Common.Exceptions;
using Application.Products.Commands;
using Domain.Entities;
using FluentAssertions;
using Infrastructure.Persistence;
using Mapster;
using MapsterMapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace WebUI.IntegrationTests.Unit.Products;

public class CreateProductCommandTests
{
    private readonly ApplicationDbContext _db;
    private readonly IMapper _mapper;

    public CreateProductCommandTests()
    {
        var opts = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        _db = new ApplicationDbContext(opts);

        var config = new TypeAdapterConfig();
        config.Scan(typeof(Application.Companies.Commands.CreateCompanyCommand).Assembly);
        _mapper = new ServiceMapper(
            new ServiceCollection()
                .AddSingleton(config)
                .AddScoped<IMapper, ServiceMapper>()
                .BuildServiceProvider(),
            config);
    }

    private EfRepository<T> Repo<T>() where T : class => new(_db);

    [Fact]
    public async Task Handle_ValidCommand_ProductWithPriceIsPersisted()
    {
        // Arrange
        var libItem = new CategoryLibraryItem { Title = "Main", Slug = "main" };
        await _db.CategoryLibraryItems.AddAsync(libItem);
        var category = new Category { MenuId = Guid.NewGuid(), CategoryLibraryItemId = libItem.Id, SortOrder = 1, IsActive = true };
        await _db.Categories.AddAsync(category);
        await _db.SaveChangesAsync();

        var handler = new CreateProductCommandHandler(Repo<Product>(), Repo<Category>(), _mapper);
        var command = new CreateProductCommand
        {
            Title = "Burger",
            BasePrice = 12.50m,
            IsActive = true,
            CategoryId = category.Id
        };

        // Act
        var result = await handler.Handle(command, CancellationToken.None);
        await _db.SaveChangesAsync();

        // Assert
        result.Should().NotBeNull();
        result.Title.Should().Be("Burger");
        result.BasePrice.Should().Be(12.50m);

        var saved = await _db.Products.FirstOrDefaultAsync(p => p.CategoryId == category.Id);
        saved.Should().NotBeNull();
        saved!.BasePrice.Should().Be(12.50m);
    }

    [Fact]
    public async Task Handle_CategoryNotFound_ThrowsUnprocessableAppException()
    {
        // Arrange — no category in DB
        var handler = new CreateProductCommandHandler(Repo<Product>(), Repo<Category>(), _mapper);
        var command = new CreateProductCommand
        {
            Title = "Pizza",
            BasePrice = 15.00m,
            IsActive = true,
            CategoryId = Guid.NewGuid()
        };

        // Act
        var act = () => handler.Handle(command, CancellationToken.None);

        // Assert
        await act.Should().ThrowAsync<UnprocessableAppException>();
    }

    [Fact]
    public async Task Handle_NoSlugProvided_SlugIsAutoGenerated()
    {
        // Arrange
        var libItem = new CategoryLibraryItem { Title = "Main", Slug = "main" };
        await _db.CategoryLibraryItems.AddAsync(libItem);
        var category = new Category { MenuId = Guid.NewGuid(), CategoryLibraryItemId = libItem.Id, SortOrder = 1, IsActive = true };
        await _db.Categories.AddAsync(category);
        await _db.SaveChangesAsync();

        var handler = new CreateProductCommandHandler(Repo<Product>(), Repo<Category>(), _mapper);
        var command = new CreateProductCommand
        {
            Title = "Adana Kebap",
            BasePrice = 20.00m,
            IsActive = true,
            CategoryId = category.Id,
            Slug = null
        };

        // Act
        var result = await handler.Handle(command, CancellationToken.None);
        await _db.SaveChangesAsync();

        // Assert
        result.Should().NotBeNull();
        var saved = await _db.Products.FirstOrDefaultAsync(p => p.CategoryId == category.Id);
        saved.Should().NotBeNull();
        saved!.Slug.Should().Be("adana-kebap");
    }
}
