using Domain.Entities;

namespace Infrastructure.Persistence;

public static class MenuDesignSeedData
{
    public static List<MenuDesign> GetDesigns() =>
    [
        new MenuDesign
        {
            Name = "Kafe & Çay",
            Slug = "kafe-cay",
            Description = "Kahve renkleri ve sıcak tonlarla tasarlanmış kafe teması",
            PrimaryColor = "#6f4e37",
            PrimaryDarkColor = "#3c2a21",
            AccentColor = "#d2691e",
            BackgroundColor = "#fdf8f3",
            SurfaceColor = "#ffffff",
            TextColor = "#1f2937",
            MutedColor = "#6b7280",
            BorderRadius = "24px",
            BackgroundGradient = null,
            BackgroundImageUrl = "/images/Menu/kafe_bg_watermark_free.jpg",
            PreviewImageUrl = "/images/Menu/kafe_bg_watermark_free.jpg",
            HeaderBackgroundColor = "#6f4e37",
            HeaderTextColor = "#ffffff",
            ButtonStyle = "solid",
            CardShadow = "0 10px 25px -5px rgba(111, 78, 55, 0.1), 0 8px 10px -6px rgba(111, 78, 55, 0.1)",
            CardBorderColor = "#fff7ed",
            CardImageBorderRadius = "12px",
            FooterBackgroundColor = "#3c2a21",
            FooterTextColor = "#d1d5db",
            FooterButtonColor = "#d2691e",
            FooterButtonStyle = "solid",
            FontFamily = "Poppins, sans-serif",
            HeadingFontFamily = "Playfair Display, serif",
            HeadingFontSize = "2.25rem",
            SubheadingFontSize = "1.5rem",
            IsDefault = true,
            SortOrder = 1,
        },
        new MenuDesign
        {
            Name = "Fast Food",
            Slug = "fast-food",
            Description = "Kırmızı-sarı renkler, sert gölgeler ve enerjik başlıklarla hızlı servis teması",
            PrimaryColor = "#d32f2f",
            PrimaryDarkColor = "#8b1c1c",
            AccentColor = "#ffeb3b",
            BackgroundColor = "#ffc107",
            SurfaceColor = "#ffffff",
            TextColor = "#333333",
            MutedColor = "#666666",
            BorderRadius = "0px",
            BackgroundGradient = "linear-gradient(135deg, #d32f2f 0%, #8b1c1c 100%)",
            BackgroundImageUrl = "/images/Menu/fastfood_bg_watermark_free.jpg",
            PreviewImageUrl = "/images/Menu/fastfood_bg_watermark_free.jpg",
            HeaderBackgroundColor = "#d32f2f",
            HeaderTextColor = "#ffffff",
            ButtonStyle = "solid",
            CardShadow = "8px 8px 0px 0px rgba(0, 0, 0, 0.8)",
            CardBorderColor = "#000000",
            CardImageBorderRadius = "0px",
            FooterBackgroundColor = "#212121",
            FooterTextColor = "#ffffff",
            FooterButtonColor = "#ffeb3b",
            FooterButtonStyle = "outline",
            FontFamily = "Rubik, sans-serif",
            HeadingFontFamily = "Bangers, cursive",
            HeadingFontSize = "3.5rem",
            SubheadingFontSize = "2rem",
            IsDefault = false,
            SortOrder = 2,
        },
        new MenuDesign
        {
            Name = "Tatlı & Pastane",
            Slug = "tatli-pastane",
            Description = "Pastel pembe tonlar, yumuşak gölgeler ve el yazısı başlıklarla tatlıcı teması",
            PrimaryColor = "#ff85a2",
            PrimaryDarkColor = "#880e4f",
            AccentColor = "#b3e5fc",
            BackgroundColor = "#fff5f7",
            SurfaceColor = "#ffffff",
            TextColor = "#5d4037",
            MutedColor = "#8d6e63",
            BorderRadius = "32px",
            BackgroundGradient = "linear-gradient(135deg, #ff85a2 0%, #fce4ec 100%)",
            BackgroundImageUrl = "/images/Menu/tatli_bg_watermark_free.jpg",
            PreviewImageUrl = "/images/Menu/tatli_bg_watermark_free.jpg",
            HeaderBackgroundColor = "#ff85a2",
            HeaderTextColor = "#ffffff",
            ButtonStyle = "solid",
            CardShadow = "0 8px 30px rgba(255, 133, 162, 0.15)",
            CardBorderColor = "#fce4ec",
            CardImageBorderRadius = "24px",
            FooterBackgroundColor = "#fce4ec",
            FooterTextColor = "#880e4f",
            FooterButtonColor = "#ff85a2",
            FooterButtonStyle = "solid",
            FontFamily = "Quicksand, sans-serif",
            HeadingFontFamily = "Pacifico, cursive",
            HeadingFontSize = "3.75rem",
            SubheadingFontSize = "2rem",
            IsDefault = false,
            SortOrder = 3,
        },
        new MenuDesign
        {
            Name = "Et Lokantası",
            Slug = "et-lokantasi",
            Description = "Koyu ahşap dokusu, bordo ve altın vurgularla steakhouse teması",
            PrimaryColor = "#4a0e0e",
            PrimaryDarkColor = "#2a0808",
            AccentColor = "#d4af37",
            BackgroundColor = "#1a1110",
            SurfaceColor = "#2d1b19",
            TextColor = "#f5f5f5",
            MutedColor = "#9ca3af",
            BorderRadius = "8px",
            BackgroundGradient = "linear-gradient(135deg, #4a0e0e 0%, #1a1110 100%)",
            BackgroundImageUrl = "/images/Menu/et_bg_watermark_free.jpg",
            PreviewImageUrl = "/images/Menu/et_bg_watermark_free.jpg",
            HeaderBackgroundColor = "#4a0e0e",
            HeaderTextColor = "#ffffff",
            ButtonStyle = "solid",
            CardShadow = "0 20px 40px rgba(0, 0, 0, 0.35)",
            CardBorderColor = "#3d2b29",
            CardImageBorderRadius = "8px",
            FooterBackgroundColor = "#2a0808",
            FooterTextColor = "#f5f5f5",
            FooterButtonColor = "#d4af37",
            FooterButtonStyle = "solid",
            FontFamily = "Roboto Condensed, sans-serif",
            HeadingFontFamily = "Oswald, sans-serif",
            HeadingFontSize = "4rem",
            SubheadingFontSize = "2rem",
            IsDefault = false,
            SortOrder = 4,
        },
        new MenuDesign
        {
            Name = "Şık Restoran",
            Slug = "sik-restoran",
            Description = "Siyah zemin, altın detaylar ve zarif serif başlıklarla fine dining teması",
            PrimaryColor = "#c5a059",
            PrimaryDarkColor = "#050505",
            AccentColor = "#c5a059",
            BackgroundColor = "#0a0a0a",
            SurfaceColor = "#1a1a1a",
            TextColor = "#e5e5e5",
            MutedColor = "#a3a3a3",
            BorderRadius = "2px",
            BackgroundGradient = "linear-gradient(135deg, #121212 0%, #050505 100%)",
            BackgroundImageUrl = "/images/Menu/restoran_bg_watermark_free.jpg",
            PreviewImageUrl = "/images/Menu/restoran_bg_watermark_free.jpg",
            HeaderBackgroundColor = "#121212",
            HeaderTextColor = "#e5e5e5",
            ButtonStyle = "outline",
            CardShadow = "0 4px 20px rgba(197, 160, 89, 0.1)",
            CardBorderColor = "#2f2f2f",
            CardImageBorderRadius = "2px",
            FooterBackgroundColor = "#050505",
            FooterTextColor = "#e5e5e5",
            FooterButtonColor = "#c5a059",
            FooterButtonStyle = "outline",
            FontFamily = "Montserrat, sans-serif",
            HeadingFontFamily = "Cinzel, serif",
            HeadingFontSize = "4rem",
            SubheadingFontSize = "2rem",
            IsDefault = false,
            SortOrder = 5,
        }
    ];
}
