using Domain.Entities;

namespace Application.MenuDesigns.DTOs;

public static class MenuDesignMappingExtensions
{
    public static MenuDesignDTO ToDto(this MenuDesign design) => new()
    {
        Id = design.Id,
        Name = design.Name,
        Slug = design.Slug,
        Description = design.Description,
        PrimaryColor = design.PrimaryColor,
        PrimaryDarkColor = design.PrimaryDarkColor,
        AccentColor = design.AccentColor,
        BackgroundColor = design.BackgroundColor,
        SurfaceColor = design.SurfaceColor,
        TextColor = design.TextColor,
        MutedColor = design.MutedColor,
        BorderRadius = design.BorderRadius,
        BackgroundGradient = design.BackgroundGradient,
        BackgroundImageUrl = design.BackgroundImageUrl,
        PreviewImageUrl = design.PreviewImageUrl,
        HeaderBackgroundColor = design.HeaderBackgroundColor,
        HeaderTextColor = design.HeaderTextColor,
        ButtonStyle = design.ButtonStyle,
        CardShadow = design.CardShadow,
        CardBorderColor = design.CardBorderColor,
        CardBorderWidth = design.CardBorderWidth,
        CardBackgroundColor = design.CardBackgroundColor,
        CardImageBorderRadius = design.CardImageBorderRadius,
        FooterBackgroundColor = design.FooterBackgroundColor,
        FooterTextColor = design.FooterTextColor,
        FooterButtonColor = design.FooterButtonColor,
        FooterButtonStyle = design.FooterButtonStyle,
        FontFamily = design.FontFamily,
        BodyFontSize = design.BodyFontSize,
        HeadingFontFamily = design.HeadingFontFamily,
        HeadingFontSize = design.HeadingFontSize,
        SubheadingFontSize = design.SubheadingFontSize,
        HeadingTextColor = design.HeadingTextColor,
        HeadingBorderWidth = design.HeadingBorderWidth,
        HeadingBorderColor = design.HeadingBorderColor,
        HeadingFontWeight = design.HeadingFontWeight,
        LinkColor = design.LinkColor,
        PriceColor = design.PriceColor,
        ButtonTextColor = design.ButtonTextColor,
        ButtonBorderColor = design.ButtonBorderColor,
        ButtonBorderRadius = design.ButtonBorderRadius,
        SurfaceOpacity = design.SurfaceOpacity,
        CardOpacity = design.CardOpacity,
        HeaderSecondaryTextOpacity = design.HeaderSecondaryTextOpacity,
        HeaderAccentTextOpacity = design.HeaderAccentTextOpacity,
        PageBackgroundOverlayOpacity = design.PageBackgroundOverlayOpacity,
        MutedTextOpacity = design.MutedTextOpacity,
        PanelOpacity = design.PanelOpacity,
        HeaderChipOpacity = design.HeaderChipOpacity,
        IsDefault = design.IsDefault,
        SortOrder = design.SortOrder
    };
}
